config/routes.rb
Rails.application.routes.draw do

  # Authentication
  devise_for :identities,
    controllers: {
      sessions:           "identities/sessions",
      passwords:          "identities/passwords",
      registrations:      "identities/registrations",
      confirmations:      "identities/confirmations",
      omniauth_callbacks: "identities/omniauth_callbacks"
    },
    # https://github.com/plataformatec/devise#configuring-routes
    path: 'auth',
    path_names: { sign_up: 'signup', sign_in: 'login', sign_out: 'logout' }

  # Ask for email address after successful OAuth.
  resources :email_confirmations, only: [:show, :update]

  # To demonstarate Pundit authorization
  resources :identities

  # Soial profiles
  resources :social_profiles

  # Frontend users
  resources :users

  # Backend users
  resources :admins, only: [:show]
  resources :account_executives, only: [:show]
  resources :management_clients, only: [:show]
  resources :property_clients, only: [:show]

  # NOTE: '/' needs to be places at the bottom of the list because we do not
  # want other paths to be ignored.
  root to: "react_pages#index"

  # For viewing delivered emails in development environment.
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/shared/_backend_dashboard.html.slim
- provide(:title, current_backend_user.name)

h1.page-header 
  = current_backend_user.name

h3 Ruby representation of me as a backend user

.well
  p = current_backend_user.inspect

hr

h3 All account_executives

ul
  - AccountExecutive.all.each do |person|
    li = person.inspect
    
hr

h3 All management_clients

ul
  - ManagementClient.all.each do |person|
    li = person.inspect
    
hr

h3 All property_clients

ul
  - PropertyClient.all.each do |person|
    li = person.inspect

app/views/shared/_social_connect.html.slim
-# Required props: provider as a symbol (:facebook, :google_oauth2, :twitter)

- connected = current_identity.try(:social_profile, provider)
- icon_name = (provider == :google_oauth2) ? "google-plus" : provider

- if connected
  = link_to fa_icon("fw #{icon_name}", text: "Disconnect"),
    social_profile_path(current_identity.social_profile(provider)), method: :delete,
    class: "btn btn-default btn-disconnect #{provider}"
- else
  = link_to fa_icon("fw #{icon_name}", text: "Connect"),
    eval("identity_#{provider}_omniauth_authorize_path"),
    class: "btn btn-primary btn-connect #{provider}"